[package]
name = "thorium_ebpf"
version = "0.1.0"
edition = "2021"

[dependencies]
aya = { version = "0.13.1", features = ["async_tokio"] }
aya-log = "0.2.1"
thorium_ebpf-common = { path = "../thorium_ebpf-common", features = ["user"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bytes = "1"
anyhow = "1.0"
